FROM openjdk:8
LABEL description="SpringBoot Application"
EXPOSE 8080
RUN git clone https://github.com/kshelp/ch02_mybatis.git
WORKDIR inbuilder
RUN chmod 700 mvnw
RUN ./mvnw clean package
RUN mv target/app-in-host.jar /opt/app-in-image.jar
WORKDIR /opt
ENTRYPOINT [ "java", "-jar", "app-in-image.jar" ]
