apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle11g-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.10  # NFS 서버의 IP 주소
    path: /nfs_shared/oracle/oradata  # NFS 공유 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle11g-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

