apiVersion: v1
kind: Service
metadata:
  name: oracle11g
spec:
  type: NodePort  # 외부 접근을 위해 NodePort 사용
  ports:
    - port: 1521
      targetPort: 1521
      nodePort: 31521  # 원하는 노드 포트 지정
  selector:
    app: oracle11g

