---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle11g
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /nfs_shared/oradata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle11g
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
