---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-xe-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /nfs_shared/oracle
    server: 192.168.1.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-xe-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
